language: node_js
node_js:
- '6'
cache:
  directories:
    - node_modules
install: npm install
before_script: NODE_ENV="production"
script: npm run build
after_script: rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: tZlBNXorEP4H1qbIgieOmcnMZ2OU71iithwDGk4B/Ozj6eocxkv/ijrUo1p4+Y69Q0JB8bqEAyxPW3DOKkOSD4NmkZomFHtgWy9vMRUZmGk4JekaEGv3ugUB31voaKZsMyk5cG8MBJyqI2Co2N4jQQyagb5IxzC7wEvMqoUU0VsO2CJ13veNu8JH3Y3E71geE0je7sLljG8UkYQCxDf8Zt5PPb8O2DWCW+M5YzG15Ql26Qc0thrF9eDBFiorinenRqlVBoJSCCr0BOeqmMCpUzPg7upNHAQp/A7dCz7bMxLvd6xf+BWAggPthOEfAnAAdOLusrJn9MsfcQWsxW6yGk35Cj9tQW/MHWsSPQ1sHnceFrRC1Zl4sJUbFHXv+xwXL8u5luFIK0RhCr50/dRPyZS2BWzbY6JUkr9eKuSYsAVIRwdTv7Q4FQegVBpR7JEKeZOTl3CbCeRQEIQjjhKu73wvygAKIENKqWUA+lGaZ8YQzjc1k/6oPUKGSuzNcdg8sqsXel//Du9Xu95mNL9uxboxl9iFQg8v7jnK0Jx647pqxvjXLNdr/jQ7Ty6DuOwqZrEBWCgTk37lHfv8C1bZwz7LDxX7TEDPW9rUq2ksidQu8pt/XbisctO0Y/X4yLLj/PG/AT0zLA+b2ZOBj7T1YfqXRTj+MkW4/7bl7PowiT4=
  app:
    master: jakepeyser
    prod_deployment_fixes: jakepeyser-test
