export default [
  { icon: 'javascript', name: 'JavaScript', link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript' },
  { icon: 'react', name: 'React', link: 'https://facebook.github.io/react/' },
  { icon: 'mobx', name: 'MobX', link: 'https://mobx.js.org/' },
  { icon: 'redux', name: 'Redux', link: 'http://redux.js.org/' },
  { icon: 'vue', name: 'Vue', link: 'https://vuejs.org/' },
  { icon: 'html', name: 'HTML5', link: 'https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5' },
  { icon: 'css', name: 'CSS3', link: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS3' },
  { icon: 'sass', name: 'Sass', link: 'http://sass-lang.com/' },
  { icon: 'stylus', name: 'Stylus', link: 'http://stylus-lang.com/' },
  { icon: 'webpack', name: 'Webpack', link: 'https://webpack.github.io/' },
  { icon: 'node', name: 'Node.js', link: 'https://nodejs.org/en/' },
  { icon: 'express', name: 'Express', link: 'https://expressjs.com/' },
  { icon: 'sequelize', name: 'Sequelize', link: 'http://docs.sequelizejs.com/' },
  { icon: 'python', name: 'Python', link: 'https://www.python.org/' },
  { icon: 'flask', name: 'Flask', link: 'http://flask.pocoo.org/' },
  { icon: 'git', name: 'Git', link: 'https://git-scm.com/' },
  { icon: 'travis', name: 'Travis CI', link: 'https://travis-ci.org/' },
  { icon: 'codeship', name: 'Codeship', link: 'https://codeship.com/' },
  { icon: 'heroku', name: 'Heroku', link: 'https://www.heroku.com/' },
  { icon: 'aws', name: 'AWS', link: 'https://aws.amazon.com/' },
  { icon: 'bluemix', name: 'Bluemix', link: 'https://console.bluemix.net/' },
  { icon: 'postgres', name: 'PostgreSQL', link: 'https://www.postgresql.org/' },
  { icon: 'elasticsearch', name: 'Elasticsearch', link: 'https://www.elastic.co/products/elasticsearch' },
  { icon: 'sketch', name: 'Sketch', link: 'https://www.sketchapp.com/' },
  { icon: 'apple', name: 'Keynote', link: 'https://www.apple.com/keynote/' }
]
